### ISSUE TITLE
Simmetrics

### ISSUE THREAD

**Issue by mpkorstanje** [dice-group/FOX#11]
Hi! I'm the current maintainer of Simmetrics.

I noticed you were using Simmetrics 1.6.2 from SourceForge and including the jar somewhat awkwardly with a system path. Simmetrics is available on Maven Central these days so you can include it just by using:

``` xml
<dependency>
    <groupId>com.github.mpkorstanje</groupId>
    <artifactId>simmetrics-core</artifactId>
    <version>3.2.0</version>
</dependency>
```

I did refactor and redesign most of the library so you'll have to re-create your metric using `StringMetric q = StringMetrics.qGramsDistance();` you can then use it by doing `q.compare(a,b)`.

Hope this makes things a tiny bit easier for you.

**Comment by renespeck** [comment]
Thanks for the hint, I will make an update soon.
