### ISSUE TITLE
Docker image for "en" fails to build

### ISSUE THREAD

**Issue by yamalight** [dice-group/FOX#35]
Current Dockerfile for "en" is broken due to following problems:

### Problem 1:
You try to copy `fox.properties-dist` from outside docker, when it should be copied on inside.
This is a simple fix (unless you want to do something else):
```
- COPY ./fox.properties-dist ./fox.properties
+ RUN cp ./fox.properties-dist ./fox.properties
```

### Problem 2:
You try to copy file that doesn't exists neither outside, nor inside. Where should it come from?
My search showed that file with that name already exists in `/data/fox/ml/en/` - is that line even needed?
```
COPY weka.classifiers.functions.MultilayerPerceptron ./data/fox/ml/en/
```

**Comment by renespeck** [comment]
The line is a relic of an older version and not needed.
