### ISSUE TITLE
Use Case: Browser Plugin

### ISSUE THREAD

**Issue by BonarBeavis** [dice-group/FOX#37]
Hi,

did you think of creating a plugin which runs fox on a visited website and which adds hover boxes to recognized entities. These hover boxes could display a summary of the corresponding wikipedia entries.
I think this could be really useful.

**Comment by renespeck** [comment]
Hi, indeed I already had this idea using https://github.com/KangoExtensions. 

I really would  like to have such a browser extension, feel free to support FOX with it.
