### ISSUE TITLE
Build Failure Issue

### ISSUE THREAD

**Issue by jiseongyee** [dice-group/FOX#54]
Hello, I am Jiseong Kim at KAIST working with AKSW for the QAMEL project.

I am writing this message because of a build failure issue on FOX.

I has been trying to install the source code cloned from the master brunch of "https://github.com/dice-group/FOX" by "mvn clean install -U",

but, I has faced this build failure message:

ERROR] Failed to execute goal on project fox: Could not resolve dependencies for project org.aksw:fox:jar:2.5.1: The following artifacts could not be resolved: org.aksw.simba.knowledgeextraction:commons:jar:0.0.1, org.aksw:ocelot:jar:0.0.1, org.semanticweb.yars:nxparser:jar:1.2.3: Could not find artifact org.aksw.simba.knowledgeextraction:commons:jar:0.0.1 in Apache Repo Central (http://repo.maven.apache.org/maven2) -> [Help 1]

Could you give me an advice for the successful installation?

It is an urgent issue since we have to show the demo of FOX on the QAMEL project evaluation.

Thanks in advance.

**Comment by renespeck** [comment]
Dear Jiseong Kim, the readme.md files points to the documentation as well as to a running demo of FOX.
