### ISSUE TITLE
Language configuration

### ISSUE THREAD

**Issue by adibaba** [dice-group/FOX#56]
Hello,

I want to enable an additional language (de). What is the best way to do that?
Currently, I am using version 2.3.0, which is the latest release. I can change to the current master (2.5.0), if necessary.

The current documentation is located at https://github.com/dice-group/FOX/tree/master/documentation

**Comment by adibaba** [comment]
Update:
The developer @renespeck told me to use this file:
https://github.com/dice-group/FOX/blob/master/data/fox/cfg/org.aksw.fox.tools.ToolsGenerator.xml

**Comment by renespeck** [comment]
Hi, the version in the master branch is the latest version, this version supports Relation Extraction. If you are interested in NER and NED only version 2.3.0 is fine. 

To change the supported languages and tools within FOX the file above is all you need.  
Except for English all other languages are using the webservice of Spotlight. Be sure the services are running.
